


DROP TABLE "USER";

-- 시퀀스 생성
CREATE SEQUENCE SEQ_USER_NO NOCACHE;

-- 1. USER TABLE 생성
-- 기본 프로필 이미지 주소 추후 default로 업로드
CREATE TABLE "USER" (
	"USER_NO"	NUMBER		NOT NULL,
	"USER_GRADE"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"USER_IMG"	VARCHAR2(1000)	NULL,                   
	"USER_EMAIL"	VARCHAR2(100)		NOT NULL,
	"USER_NICKNAME"	VARCHAR2(30)		NOT NULL,
	"USER_PW"	VARCHAR2(100)		NOT NULL,
	"USER_ADD"	VARCHAR2(1000)		NOT NULL,
	"USER_ABOUT_ME"	CLOB		NULL,
	"USER_SOCIAL_LOGIN"	VARCHAR2(100)		NULL,
	"USER_ENDROLL_DT"	DATE	DEFAULT SYSDATE	NULL,
	"USER_REPORTED"	NUMBER	DEFAULT 0	NOT NULL,
	"USER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NULL
);



COMMENT ON COLUMN "USER"."USER_NO" IS '회원 번호(SEQ_USER_NO)';
COMMENT ON COLUMN "USER"."USER_GRADE" IS '회원 등급(1:일반/2:관리자)';
COMMENT ON COLUMN "USER"."USER_IMG" IS '회원 이미지(이미지주소)';
COMMENT ON COLUMN "USER"."USER_EMAIL" IS '회원 이메일(중복불가)';
COMMENT ON COLUMN "USER"."USER_NICKNAME" IS '회원 닉네임(중복불가)';
COMMENT ON COLUMN "USER"."USER_PW" IS '회원 비밀번호(암호화)';
COMMENT ON COLUMN "USER"."USER_ADD" IS '회원 주소';
COMMENT ON COLUMN "USER"."USER_ABOUT_ME" IS '회원 자기소개';
COMMENT ON COLUMN "USER"."USER_SOCIAL_LOGIN" IS '회원 소셜로그인(카카오톡)';
COMMENT ON COLUMN "USER"."USER_ENDROLL_DT" IS '회원 가입일';
COMMENT ON COLUMN "USER"."USER_REPORTED" IS '회원 신고당한 횟수';
COMMENT ON COLUMN "USER"."USER_DEL_FL" IS '회원 탈퇴여부(Y:탈퇴/N:탈퇴X)';

ALTER TABLE "USER" ADD CONSTRAINT "CH_USER_GRADE" CHECK ("USER_GRADE" IN ('1', '2'));
ALTER TABLE "USER" ADD CONSTRAINT "CH_USER_DEL_FL" CHECK ("USER_DEL_FL" IN ('Y', 'N'));

ALTER TABLE "USER" ADD CONSTRAINT "PK_USER" PRIMARY KEY (
	"USER_NO"
);



-- 테이블 확인
SELECT * FROM "USER";





DROP TABLE "PETTITION";

-- 시퀀스 생성
CREATE SEQUENCE SEQ_PT_NO NOCACHE;

-- 2. PETTITION TABLE 생성
CREATE TABLE "PETTITION" (
	"PT_NO"	NUMBER		NOT NULL,
	"PT_TITLE"	VARCHAR2(2000)		NOT NULL,
	"PT_CONTENT"	VARCHAR2(3000)		NULL,
	"PT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PT_VIEW_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"PT_LIKE_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"PT_VICT"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"PT_IMG"	VARCHAR2(1000)	NULL,
	"PT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"CAT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PETTITION"."PT_NO" IS '글번호(SEQ_PT_NO)';
COMMENT ON COLUMN "PETTITION"."PT_TITLE" IS '글 제목';
COMMENT ON COLUMN "PETTITION"."PT_CONTENT" IS '글 내용';
COMMENT ON COLUMN "PETTITION"."PT_DATE" IS '작성일';
COMMENT ON COLUMN "PETTITION"."PT_VIEW_COUNT" IS '글 조회수';
COMMENT ON COLUMN "PETTITION"."PT_LIKE_COUNT" IS '글 좋아요 수';
COMMENT ON COLUMN "PETTITION"."PT_VICT" IS '승리여부(Y:승리 N:승리X)';
COMMENT ON COLUMN "PETTITION"."PT_IMG" IS '글 이미지';
COMMENT ON COLUMN "PETTITION"."PT_DEL_FL" IS '글 삭제 여부(Y:삭제/N:삭제X)';
COMMENT ON COLUMN "PETTITION"."USER_NO" IS '회원번호(SEQ_USER_NO)';
COMMENT ON COLUMN "PETTITION"."CAT_NO" IS '카테고리 코드(SEQ_CAT_NO)';

-- CHECKED 제약조건
ALTER TABLE "PETTITION" ADD CONSTRAINT "CH_PT_VICT" CHECK ("PT_VICT" IN ('Y', 'N'));
ALTER TABLE "PETTITION" ADD CONSTRAINT "CH_PT_DEL_FL" CHECK ("PT_DEL_FL" IN ('Y', 'N'));


-- 기본키
ALTER TABLE "PETTITION" ADD CONSTRAINT "PK_PETTITION" PRIMARY KEY (
	"PT_NO"
);




-- 테이블 확인
SELECT * FROM "PETTITION";








DROP TABLE "PETTITION_UPDATE";


-- 시퀀스 생성
CREATE SEQUENCE SEQ_UP_NO NOCACHE;

-- 3. PETTITION_UPDATE 생성
CREATE TABLE "PETTITION_UPDATE" (
	"UP_NO"	NUMBER		NOT NULL,
	"UP_TITLE"	VARCHAR2(600)		NOT NULL,
	"UP_CONTENT"	CLOB		NOT NULL,
	"UP_CREATE_DT"	DATE		NOT NULL,
	"UP_IMG"	VARCHAR2(1000)		NULL,
	"UP_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"PT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PETTITION_UPDATE"."UP_NO" IS '업데이트 글번호(SEQ_UP_NO)';
COMMENT ON COLUMN "PETTITION_UPDATE"."UP_TITLE" IS '업데이트  제목';
COMMENT ON COLUMN "PETTITION_UPDATE"."UP_CONTENT" IS '업데이트 내용';
COMMENT ON COLUMN "PETTITION_UPDATE"."UP_CREATE_DT" IS '업데이트  작성일';
COMMENT ON COLUMN "PETTITION_UPDATE"."UP_IMG" IS '업데이트 이미지';
COMMENT ON COLUMN "PETTITION_UPDATE"."UP_DEL_FL" IS '업데이트 삭제여부';
COMMENT ON COLUMN "PETTITION_UPDATE"."PT_NO" IS '글번호(SEQ_PT_NO)';


-- CHECKED 제약조건
ALTER TABLE "PETTITION_UPDATE" ADD CONSTRAINT "CH_UP_DEL_FL" CHECK ("UP_DEL_FL" IN ('Y', 'N'));

-- 기본키
ALTER TABLE "PETTITION_UPDATE" ADD CONSTRAINT "PK_PETTITION_UPDATE" PRIMARY KEY (
	"UP_NO"
);








DROP TABLE "COMMENT";



-- 시퀀스 생성
CREATE SEQUENCE SEQ_CM_NO NOCACHE;

-- 4. COMMENT 생성
CREATE TABLE "COMMENT" (
	"CM_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"PT_NO"	NUMBER		NOT NULL,
	"CM_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"CM_DATE"	DATE		NOT NULL,
	"CM_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "COMMENT"."CM_NO" IS '댓글 번호(SEQ_CM_NO)';
COMMENT ON COLUMN "COMMENT"."USER_NO" IS '회원번호(SEQ_USER_NO)';
COMMENT ON COLUMN "COMMENT"."PT_NO" IS '글번호(SEQ_PT_NO)';
COMMENT ON COLUMN "COMMENT"."CM_CONTENT" IS '댓글 내용';
COMMENT ON COLUMN "COMMENT"."CM_DATE" IS '댓글 작성일';
COMMENT ON COLUMN "COMMENT"."CM_DEL_FL" IS '댓글 삭제(삭제:Y, 유지:N)';


-- CHECKED 제약조건
ALTER TABLE "COMMENT" ADD CONSTRAINT "CH_CM_DEL_FL" CHECK ("CM_DEL_FL" IN ('Y', 'N'));

-- 기본키
ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"CM_NO"
);










DROP TABLE "PETTITION_LIKE";

-- 시퀀스 생성
CREATE SEQUENCE SEQ_PT_LIKE_NO NOCACHE;
-- 5. PETTITION_LIKE 생성
CREATE TABLE "PETTITION_LIKE" (
	"PT_LIKE_NO"	NUMBER		NULL,
	"PT_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PETTITION_LIKE"."PT_LIKE_NO" IS '청원 좋아요 번호(SEQ_PT_LIKE_NO)';
COMMENT ON COLUMN "PETTITION_LIKE"."PT_NO" IS '글번호(SEQ_PT_NO)';
COMMENT ON COLUMN "PETTITION_LIKE"."USER_NO" IS '회원 번호(SEQ_USER_NO)';



-- 기본키
ALTER TABLE "PETTITION_LIKE" ADD CONSTRAINT "PK_PETTITION_LIKE" PRIMARY KEY (
	"PT_LIKE_NO"
);









DROP TABLE "COMMENT_LIKE";

-- 시퀀스 생성
CREATE SEQUENCE SEQ_CM_LIKE_NO NOCACHE;

-- 6. COMMENT_LIKE 생성
CREATE TABLE "COMMENT_LIKE" (
	"CM_LIKE_NO"	NUMBER		NOT NULL,
	"CM_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMMENT_LIKE"."CM_LIKE_NO" IS '댓글 좋아요  번호(SEQ_CM_NO)';
COMMENT ON COLUMN "COMMENT_LIKE"."CM_NO" IS '댓글 번호(SEQ_CM_NO)';
COMMENT ON COLUMN "COMMENT_LIKE"."USER_NO" IS '회원  번호(SEQ_USER_NO)';


-- 기본키
ALTER TABLE "COMMENT_LIKE" ADD CONSTRAINT "PK_COMMENT_LIKE" PRIMARY KEY (
	"CM_LIKE_NO",
	"CM_NO",
	"USER_NO"
);












DROP TABLE "PETTITION_CATEGORY";


-- 시퀀스 생성
CREATE SEQUENCE SEQ_CAT_NO NOCACHE;
-- 7. PETTITION_CATEGORY 생성
CREATE TABLE "PETTITION_CATEGORY" (
	"CAT_NO"	NUMBER		NOT NULL,
	"CAT_NAME"	VARCHAR2(300)		NOT NULL,
	"CAT_MAIN_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "PETTITION_CATEGORY"."CAT_NO" IS '카테고리 코드(SEQ_CAT_NO)';
COMMENT ON COLUMN "PETTITION_CATEGORY"."CAT_NAME" IS '카테고리 이름';
COMMENT ON COLUMN "PETTITION_CATEGORY"."CAT_MAIN_FL" IS '카테고리 메인 노출여부(Y:기본카테고리/N:회원이 생성한 카테고리)';

-- CHECKED 제약조건
ALTER TABLE "PETTITION_CATEGORY" ADD CONSTRAINT "CH_CAT_MAIN_FL" CHECK ("CAT_MAIN_FL" IN ('Y', 'N'));

-- 기본키
ALTER TABLE "PETTITION_CATEGORY" ADD CONSTRAINT "PK_PETTITION_CATEGORY" PRIMARY KEY (
	"CAT_NO"
);





DROP TABLE "FAQ";

-- 시퀀스 생성
CREATE SEQUENCE SEQ_FAQ_NO NOCACHE;

-- 8. FAQ 생성
CREATE TABLE "FAQ" (
	"FAQ_NO"	NUMBER		NOT NULL,
	"FAQ_CAT_CODE"	NUMBER		NULL,
	"FAQ_QUETIONI"	VARCHAR2(2000)		NULL,
	"FAQ_ANSWER"	CLOB		NULL
);

COMMENT ON COLUMN "FAQ"."FAQ_NO" IS 'FAQ번호 (SEQ_FAQ_NO)';
COMMENT ON COLUMN "FAQ"."FAQ_CAT_CODE" IS 'FAQ 질문 분류코드';
COMMENT ON COLUMN "FAQ"."FAQ_QUETIONI" IS 'FAQ 질문';
COMMENT ON COLUMN "FAQ"."FAQ_ANSWER" IS 'FAQ  답변';

-- 기본키
ALTER TABLE "FAQ" ADD CONSTRAINT "PK_FAQ" PRIMARY KEY (
	"FAQ_NO"
);






DROP TABLE "QNA";

-- 시퀀스 생성
CREATE SEQUENCE SEQ_QNA NOCACHE;

-- 9. PETTITION_UPDATE 생성
CREATE TABLE "QNA" (
	"QNA_NO"	VARCHAR2(100)		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"QNA_CAT_CODE"	NUMBER		NOT NULL,
	"QNA_STATUS"	CHAR(1)	DEFAULT '1'	NOT NULL,
	"QNA_TITLE"	VARCHAR2(100)		NOT NULL,
	"QNA_CONT"	CLOB		NOT NULL,
	"QNA_CREATE_DT"	VARCHAR2(100)	DEFAULT SYSDATE	NOT NULL,
	"QNA_ANSWER"	CLOB		NULL,
	"QNA_COMPLETED_DT"	VARCHAR2(100)  NULL,
	"QNA_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);


COMMENT ON COLUMN "QNA"."QNA_NO" IS '문의 번호(SEQ_QNA_NO)';
COMMENT ON COLUMN "QNA"."USER_NO" IS '회원 번호(SEQ_USER_NO)';
COMMENT ON COLUMN "QNA"."QNA_CAT_CODE" IS '문의 분류코드';
COMMENT ON COLUMN "QNA"."QNA_STATUS" IS '문의상태(1:문의대기, 2:진행중, 3:해결완료)';
COMMENT ON COLUMN "QNA"."QNA_TITLE" IS '문의  제목';
COMMENT ON COLUMN "QNA"."QNA_CONT" IS '문의 내용';
COMMENT ON COLUMN "QNA"."QNA_CREATE_DT" IS '문의 생성일자';
COMMENT ON COLUMN "QNA"."QNA_ANSWER" IS '문의답변';
COMMENT ON COLUMN "QNA"."QNA_COMPLETED_DT" IS '문의 완료일자';
COMMENT ON COLUMN "QNA"."QNA_DEL_FL" IS '문의 삭제(Y:삭제/N:삭제X)';


-- CHECKED 제약조건
ALTER TABLE "QNA" ADD CONSTRAINT "CH_QNA_STATUS" CHECK ("QNA_STATUS" IN ('1', '2', '3'));
ALTER TABLE "QNA" ADD CONSTRAINT "CH_QNA_DEL_FL" CHECK ("QNA_DEL_FL" IN ('Y', 'N'));



-- 기본키
ALTER TABLE "QNA" ADD CONSTRAINT "PK_QNA" PRIMARY KEY (
	"QNA_NO"
);












DROP TABLE "DAILYSTATE";


-- 10. PETTITION_UPDATE 생성
CREATE TABLE "DAILYSTATE" (
	"MANAGE_DATE"	DATE		NOT NULL,
	"USER_NO"	NUMBER	NOT NULL,
	"QNA_NO"	VARCHAR2(100)		NOT NULL,
	"USER_VISIT"	NUMBER	DEFAULT 0 NOT NULL
);

COMMENT ON COLUMN "DAILYSTATE"."MANAGE_DATE" IS '관리일자';
COMMENT ON COLUMN "DAILYSTATE"."USER_NO" IS '회원 번호(SEQ_USER_NO)';
COMMENT ON COLUMN "DAILYSTATE"."QNA_NO" IS '문의 번호(SEQ_QNA_NO)';
COMMENT ON COLUMN "DAILYSTATE"."USER_VISIT" IS '방문자수';

-- 기본키
ALTER TABLE "DAILYSTATE" ADD CONSTRAINT "PK_DAILYSTATE" PRIMARY KEY (
	"MANAGE_DATE"
);





-- PETTITION 외래키
ALTER TABLE "PETTITION" ADD CONSTRAINT "FK_USER_TO_PETTITION_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);
ALTER TABLE "PETTITION" ADD CONSTRAINT "FK_PETTITION_CATEGORY_TO_PETTITION_1" FOREIGN KEY (
	"CAT_NO"
)
REFERENCES "PETTITION_CATEGORY" (
	"CAT_NO"
);


-- PETTITION_UPDATE 외래키
ALTER TABLE "PETTITION_UPDATE" ADD CONSTRAINT "FK_PETTITION_TO_PETTITION_UPDATE_1" FOREIGN KEY (
	"PT_NO"
)
REFERENCES "PETTITION" (
	"PT_NO"
);

-- COMMENT 외래키
ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_USER_TO_COMMENT_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_PETTITION_TO_COMMENT_1" FOREIGN KEY (
	"PT_NO"
)
REFERENCES "PETTITION" (
	"PT_NO"
);



-- PETTITION_LIKE 외래키
ALTER TABLE "PETTITION_LIKE" ADD CONSTRAINT "FK_PETTITION_TO_PETTITION_LIKE_1" FOREIGN KEY (
	"PT_NO"
)
REFERENCES "PETTITION" (
	"PT_NO"
);

ALTER TABLE "PETTITION_LIKE" ADD CONSTRAINT "FK_USER_TO_PETTITION_LIKE_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);



-- COMMENT_LIKE 외래키
ALTER TABLE "COMMENT_LIKE" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_LIKE_1" FOREIGN KEY (
	"CM_NO"
)
REFERENCES "COMMENT" (
	"CM_NO"
);

ALTER TABLE "COMMENT_LIKE" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_LIKE_2" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);


-- QNA 외래키
ALTER TABLE "QNA" ADD CONSTRAINT "FK_USER_TO_QNA_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);

-- DAILYSTATE 외래키
ALTER TABLE "DAILYSTATE" ADD CONSTRAINT "FK_USER_TO_DAILYSTATE_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);

ALTER TABLE "DAILYSTATE" ADD CONSTRAINT "FK_QNA_TO_DAILYSTATE_1" FOREIGN KEY (
	"QNA_NO"
)
REFERENCES "QNA" (
	"QNA_NO"
);









-- USER 샘플값 입력
INSERT INTO "USER"
VALUES (SEQ_USER_NO.NEXTVAL, '2', NULL, 'user01@kh.or.kr', '유저일(관리자)', 'pass01!', '04540,,서울시 중구 남대문로 120,,2층',
'안녕하세요 유저일입니다.', NULL, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO "USER"
VALUES (SEQ_USER_NO.NEXTVAL, DEFAULT, NULL, 'user02@kh.or.kr', '유저이번', 'pass02!', '13529,,경기 성남시 분당구 백현동 532,,카카오 판교 아지트',
'안녕 유저이번입니다.', NULL, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO "USER"
VALUES (SEQ_USER_NO.NEXTVAL, DEFAULT, NULL, 'user03@kh.or.kr', '유저3', 'pass03!', '63309,,제주특별자치도 제주시 첨단로 216-18,,다음스페이스닷키즈',
'Hi, Im user3.', NULL, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO "USER"
VALUES (SEQ_USER_NO.NEXTVAL, DEFAULT, NULL, 'user03@kh.or.kr', '유저3', 'pass03!', '63309,,제주특별자치도 제주시 첨단로 216-18,,다음스페이스닷키즈',
'Hi, Im user3.', NULL, DEFAULT, DEFAULT, DEFAULT);


-- PETTITION CATEGORY 샘플값 입력
INSERT INTO "PETTITION_CATEGORY" 
VALUES (SEQ_CAT_NO.NEXTVAL, '환경', DEFAULT);
INSERT INTO "PETTITION_CATEGORY" 
VALUES (SEQ_CAT_NO.NEXTVAL, '동물', DEFAULT);
INSERT INTO "PETTITION_CATEGORY" 
VALUES (SEQ_CAT_NO.NEXTVAL, '건강', DEFAULT);
INSERT INTO "PETTITION_CATEGORY" 
VALUES (SEQ_CAT_NO.NEXTVAL, '인권', DEFAULT);



-- PETTITION 샘플값 입력
INSERT INTO "PETTITION" 
VALUES (SEQ_PT_NO.NEXTVAL, '사이트가 너무 텅 비었어요', '나만 있는 듯', DEFAULT , DEFAULT, DEFAULT, DEFAULT, NULL,
DEFAULT, 2, 1);
INSERT INTO "PETTITION" 
VALUES (SEQ_PT_NO.NEXTVAL, '순덕이 아빠가 순덕이한테 간식을 안 줌', '규탄하라 규탄하라', DEFAULT , DEFAULT, DEFAULT, 'Y', NULL,
DEFAULT, 3, 2);


-- FAQ 샘플값 입력
-- 질문분류 예시 1. 회원가입 / 2. 청원작성 / 3. 건의 등등
INSERT INTO "FAQ" 
VALUES (SEQ_FAQ_NO.NEXTVAL, 1, '회원 가입이 안 돼요', '그렇게됐다..');


COMMIT;




-- 테이블 확인
SELECT * FROM "USER";
SELECT * FROM "COMMENT" ;
SELECT * FROM "COMMENT_LIKE" ;
SELECT * FROM "DAILYSTATE";
SELECT * FROM "FAQ";
SELECT * FROM "PETTITION_CATEGORY";
SELECT * FROM "PETTITION";
SELECT * FROM "PETTITION_LIKE";
SELECT * FROM "PETTITION_UPDATE";
SELECT * FROM "QNA";





